const { GoogleSpreadsheet } = require('google-spreadsheet');

const main = async () => {
  const creds = require('./credentials.json');
  // Initialize the sheet - doc ID is the long id in the sheets URL
  const doc = new GoogleSpreadsheet('1WmSnVprRZLKoZyoonSZFbRuqe3dhOaPQzeW-aOuYiPM');

  await doc.useServiceAccountAuth(creds);
  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  // await doc.useServiceAccountAuth({
  //   // env var values are copied from service account credentials generated by google
  //   // see "Authentication" section in docs for more info
  //   client_email: 'registration@warranty-378700.iam.gserviceaccount.com',
  //   private_key: '098f129100d33e8e1b7ffa7b51a795441c7c37e7',
  // });

  await doc.loadInfo(); // loads document properties and worksheets
  console.log(doc.title);
  // await doc.updateProperties({ title: 'renamed doc' });

  const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
  console.log(sheet.title);
  console.log(sheet.rowCount);
}
main();
